# Generated by Django 6.0.5 on 2026-06-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LightFeed", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="lightfeed_user_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Readers"),
                    ("journalist", "Journalists"),
                    ("editor", "Editors"),
                ],
                default="reader",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="lightfeed_user_set", to="auth.permission"
            ),
        ),
        migrations.DeleteModel(
            name="ResetToken",
        ),
    ]
