# Generated by Django 6.0.5 on 2026-06-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LightFeed", "0002_alter_user_groups_alter_user_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="LightFeed.publisher",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Pending Editor Approval"),
                    ("published", "Published Successfully"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
    ]
