# Generated by Django 6.0.5 on 2026-06-25 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LightFeed', '0005_remove_publisher_editor_newsletter_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='LightFeed.publisher'),
        ),
    ]
